# Generated by Django 5.2.5 on 2025-08-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='gender_category',
            field=models.CharField(choices=[('her', 'For Her'), ('him', 'For Him'), ('them', 'For Them')], default='them', max_length=4),
        ),
    ]
